"""Polish, editor-compatible adaptation of motion-video-kit (MIT)."""
PLAYBOOK = {
    "source": {"repository":"https://github.com/echris6/motion-video-kit", "commit":"255562b04b1e5ecaa4ba98e5c9aa191d5ba7f6fa", "license":"MIT", "notice":"licenses/Motion-Video-Kit-MIT.txt"},
    "brief": ["Kto ogląda i jaki problem rozwiązujemy?", "Jeden komunikat i jeden następny krok (CTA)",
              "Tylko potwierdzone fakty; koncept i obrazy AI oznacz jawnie", "Rzeczywiste materiały, marka, czas i formaty",
              "Referencje z konkretnymi czasami i kryteria odrzucenia"],
    "motionRules": [
        "Element pierwszego planu może poprowadzić przejście; nowa scena jest gotowa pod nim.",
        "Zachowaj jeden rozpoznawalny obiekt pomiędzy stanami, zamiast serii niezwiązanych wejść.",
        "Jedno główne działanie, potem wspierające detale; gęstość wynika z hierarchii.",
        "Czytelne osiadanie, szybkie wyjście, zwalniające wejście. Nie dryfuj stale z tą samą prędkością.",
        "Cięcie może być płynne, jeśli zachowuje obiekt, kierunek, skalę lub język materiałów.",
        "Działanie daje widoczny wynik: wybór → rozwinięcie, pytanie → odpowiedź, problem → rozwiązanie.",
    ],
    "mechanisms": [
        {"name":"Wybrany element → szczegół", "recipe":"Zachowaj ilustrację na osi czasu przez dwa beaty; klatkami x/y/scale zmień ją w główny obiekt kolejnej sceny."},
        {"name":"Stała oś", "recipe":"Zachowaj linię lub kształt; zmieniaj teksty wokół tego samego punktu. Nagłówki nie nakładają się w czasie."},
        {"name":"Wynik powstaje etapami", "recipe":"Najpierw rama, potem dane i potwierdzenie. Użyj stagger startów klipów oraz krótszych wejść podpisów."},
        {"name":"Natłok → jeden temat", "recipe":"Wygaszaj drugorzędne elementy przez klatki opacity, powiększ wybrany obiekt przez scale, zachowaj jego pozycję docelową."},
        {"name":"Spójne cięcie", "recipe":"Ustaw obiekt w tej samej pozycji po obu stronach cięcia. Dopasuj kierunek ruchu i sprawdź klatki ±1/FPS."},
        {"name":"Kolor przejmuje kadr", "recipe":"Użyj jednego tła z list_backgrounds jako akcentu marki. Ogranicz zmiany palety, by kolor miał znaczenie."},
    ],
    "composition": ["Pierwsza klatka daje kontekst, bez przypadkowej pustki.",
                    "Jeden lub dwa cele czytania; tekst nad filmem potrzebuje spokojnego podkładu.",
                    "Zmieniaj skalę ujęć, a nie tylko animację wejścia.",
                    "Czytelne CTA na telefonie przez około 1,5 s; celowe pauzy są dozwolone.",
                    "Następny krok i sens filmu muszą być jasne także bez dźwięku."],
    "audio": ["Muzyka pasuje do odbiorcy; dynamiczny miks nie jest domyślny dla każdego filmu.",
              "Efekt dźwiękowy wspiera rzeczywistą akcję, nie każdy pojawiający się napis.",
              "Sprawdź fadeIn/fadeOut, zakończenie na logo i pełny odsłuch.",
              "analyze_export mierzy gotowy miks; profil jest orientacyjnym punktem odniesienia.",
              "Nie deklaruj odsłuchu na podstawie LUFS. Narzędzie nie wykonuje normalizacji ani limiterowania."],
    "review": {
        "independence":"Montażysta nie zatwierdza sam własnej jakości kreatywnej. Przekaż dowody człowiekowi albo świeżej sesji krytyka; to instrukcja, nie techniczne sprawdzanie tożsamości.",
        "criticInput":["Rzeczywisty MP4 i plansza create_review", "Brief i referencje", "Raport analyze_export", "Lista problemów poprzedniej rundy — bez uzasadnień autora"],
        "criticPrompt":"Oceń rzeczywisty artefakt. Sprawdź otwarcie, cel na wyciszeniu, hierarchię, tekst i przejścia. Podaj czas, obserwowany problem, wagę i kryterium poprawy. Dla każdego poprzedniego problemu zapisz NAPRAWIONE / CZĘŚCIOWO / NADAL. Szukaj regresji. Oddziel to, co obejrzano, zmierzono i odsłuchano. Zakończ GOTOWE / KOLEJNA POPRAWKA z uzasadnieniem.",
        "ledgerColumns":["runda", "job_id / review_id", "rewizja / SHA256 filmu", "krytyk", "czas", "problem", "zmiana", "weryfikacja", "pomiar przed / po"],
        "stop":"Najpierw największy problem. Dwie autonomiczne rundy zgodnie z zasadami FrameCore; dalej przedstaw dowody i decyzję potrzebną od użytkownika. Nie rozciągaj pracy o poprawki kosmetyczne.",
    },
    "tools":["get_production_status", "set_production_contract", "set_scene_beat", "propose_changes", "set_keyframes", "apply_motion_rules", "create_review", "review_verdict", "export", "get_job", "analyze_export", "get_quality_report", "package_delivery"],
    "limits":"Receptury używają istniejących klipów i klatek kluczowych. To nie są nowe efekty 3D ani automatyczny agent-krytyk. Materiały referencyjnych filmów nie są redystrybuowane. Kontrast, kolory marki, sens historii i smak muzyczny wymagają osobnej oceny.",
}
